spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/Books
    username: apple
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto-creates tables; use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata   # ðŸ‘ˆ ensures all timestamps are stored in IST
        format_sql: true
server:
  error:
    include-stacktrace: never
    include-message: always
